"use strict";
let places = ['america', 'norway', 'germany', 'india', 'england'];
console.log(`original order ${places}`);
console.log('alphabetical order', [...places].sort());
console.log('original order', places);
console.log('reverse alphabetical order', [...places].sort().reverse());
console.log('original order', places);
places.reverse;
console.log('reversed order', places);
places.reverse;
console.log('original order', places);
places.sort;
console.log('alphbetical order', places);
